### ISSUE TITLE
please fill out all fields

### ISSUE THREAD

**Issue by iraizo** [gLevaa/moonlight-admin#2]
put in user/password still dosent let me login

**Comment by gLevaa** [comment]
Try now.

**Comment by juanyRiveraa** [comment]
I have the same problem

**Comment by gLevaa** [comment]
I haven't looked at my GitHub in almost a year, apologies for the late reply.

This is due to `mysqli_real_escape_string()` returning null/empty strings as a result of no connection information to your database. Please ensure you have edited the connections file for your MySQL database.
